lib/tailwind_alpine_web/router.ex
defmodule TailwindAlpineWeb.Router do
  use TailwindAlpineWeb, :router

  import TailwindAlpineWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TailwindAlpineWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TailwindAlpineWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TailwindAlpineWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TailwindAlpineWeb.Telemetry, ecto_repos: [TailwindAlpine.Repo]
    end
  end

  ## Authentication routes

  scope "/", TailwindAlpineWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :put_session_layout]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", TailwindAlpineWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", TailwindAlpineWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/tailwind_alpine_web/controllers/user_session_controller.ex
defmodule TailwindAlpineWeb.UserSessionController do
  use TailwindAlpineWeb, :controller

  alias TailwindAlpine.Accounts
  alias TailwindAlpineWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/tailwind_alpine_web/views/user_session_view.ex
defmodule TailwindAlpineWeb.UserSessionView do
  use TailwindAlpineWeb, :view
end

lib/tailwind_alpine_web/templates/user_session/new.html.eex
<h3 class="text-xl text-gray-600 dark:text-gray-200 text-center">Log in</h3>

<%= form_for @conn, Routes.user_session_path(@conn, :create), [as: :user], fn f -> %>
  <%= if @error_message do %>
    <div class="alert alert-danger">
      <small><%= @error_message %></small>
    </div>
  <% end %>

  <div class="mt-4">
    <%= label f, :email, class: "block text-gray-600 dark:text-gray-200 text-sm font-medium mb-2" %>
    <%= text_input f, :email, required: true, class: "form-control" %>
  </div>

  <div class="mt-4">
    <div class="flex justify-between">
      <%= label f, :password, class: "block text-gray-600 dark:text-gray-200 text-sm font-medium mb-2" %>
      <%= link "Forgot password?", to: Routes.user_reset_password_path(@conn, :new), class: "text-xs text-gray-500 dark:text-gray-300 hover:underline" %>
    </div>

    <%= password_input f, :password, required: true, class: "form-control" %>
  </div>

  <div class="mt-4">
    <%= label f, :remember_me, class: "block text-gray-600 dark:text-gray-200 text-sm font-medium mb-2" do %>
      <%= checkbox f, :remember_me, class: "form-checkbox" %>
      <span class="ml-1">Keep me logged in for 60 days</span>
    <% end %>
  </div>

  <div class="mt-8">
    <%= submit "Log in", class: "btn btn-primary w-full" %>
  </div>
<% end %>

<div class="mt-6 flex items-center justify-between">
  <span class="border-b dark:border-gray-600 w-1/5 md:w-1/4"></span>

  <%= link "Or Register", to: Routes.user_registration_path(@conn, :new), class: "text-xs text-gray-500 dark:text-gray-400 uppercase hover:underline" %>

  <span class="border-b dark:border-gray-600 w-1/5 md:w-1/4"></span>
</div>